### ISSUE TITLE
macOS 11 beta 3 ошибка запуска

### ISSUE THREAD

**Issue by PavlovMD** [Andrej-Antipov/MountEFI#2]
Привет. Информирую, что при запуске на beta 3 запуск прерывается.
![Снимок экрана 2020-07-23 в 13 56 37](https://user-images.githubusercontent.com/32665280/88279462-c9e81600-ccec-11ea-9cf9-58220c6b7027.png)

**Comment by Andrej-Antipov** [comment]
Была проблема с terminal notifier. Это сообщение стаб,  в одной из прошлых редакций. К настоящему времени исправлено.  (Последняя редакция на момент написания 055)
