### ISSUE TITLE
Doesn't play well with iterm

### ISSUE THREAD

**Issue by paour** [Andrej-Antipov/MountEFI#3]
I like what you're doing with this utility (saving password, color output, etc.). I use iterm rather than Terminal.app, but the script assumes it's launched from the Finder, so it always tries to run Terminal.app.

Looking at the code I realize that since it's using a lot of scripting, untangling it from Terminal would be challenging…

**Comment by Andrej-Antipov** [comment]
Yes. It has too many function bent to terminal applet.
