### ISSUE TITLE
can't use any version with keychain password saving feature

### ISSUE THREAD

**Issue by big-mak** [Andrej-Antipov/MountEFI#4]
Great app but been encountering issues since updating to the latest versions:
when trying to mount a partition
![Screenshot 2021-10-22 at 14 32 07](https://user-images.githubusercontent.com/82375998/138462359-1254073d-067b-435f-b2a0-291eb6b7b79a.png)
when trying to edit settings
![Screenshot 2021-10-22 at 14 29 09](https://user-images.githubusercontent.com/82375998/138462012-a7e9113c-4deb-4edf-8564-fb2322ba23c9.png)

versions prior to 1.8 work perfectly, any help would be appreciated

**Comment by Andrej-Antipov** [comment]
It looks like the terminal has not permission to to call apple System Event API. 
"Not authorised to send Apple Event.
You need to enable that.

**Comment by Andrej-Antipov** [comment]
Open System Settings - Security & Privacy -Privacy - Automation and look at checkbox for the terminal and System Events
It must be enabled
<img width="644" alt="Screenshot at Oct 27 23-02-46" src="https://user-images.githubusercontent.com/36465597/139139050-38c11547-b2e0-4952-9f29-685c4e098a2e.png">
It is needed to show the password dialog window and other dialog windows.

**Comment by Andrej-Antipov** [comment]
Further If you see the dialog window like this - press OK. This permissions need to access Apple Script API by MountEFI (terminal applet)
<img width="300" alt="Screenshot 2021-10-27 at 23 09 23" src="https://user-images.githubusercontent.com/36465597/139139705-73a2822a-3532-4552-b8b1-cad92f6789a7.png">

**Comment by Andrej-Antipov** [comment]
I have added the permissions control to version 190-014 to avoid this issue in future. 
Can be build with Make_Applet command from Master or will be released soon.
