### ISSUE TITLE
Mounting wrong EFI partition with automount / CONF / EFICONF

### ISSUE THREAD

**Issue by paralyser** [Andrej-Antipov/MountEFI#5]
Hey. 
 First of all, all other functions seems to be working on Monterey 12.1.
 With multiple EFI partitions it mounts the wrong one. I have 2 NVME and 4 other sata ssd s. It usually mounts NVME from disk0 slot, however I have my Monterey Installed on NVME disk1 slot. With manual mount it mounts fine, and recognizes Opencore bootloader on it.
It gives me this error, maybe it helps :  " eThere is no active layout with name in the default prefix"" "

**Comment by Andrej-Antipov** [comment]
This error with auto switch language function
With two language system appears once after fresh install before first manual switch system layout. 
I'll check the behavior on single layout system. 

The applets support MountEFI config file and get targets from it. To setup the one you need to mount, just once open MountEFI, press P and number EFI to mount. After that CONF and EFICONF will be mount the EFI you choose.
If the targets not set, the applets mount EFI of disk with the current system. This is default behavior
